### ISSUE TITLE
Only Topdown2D currently working (GB Studio 4)

### ISSUE THREAD

**Issue by Steinbeuge** [Mico27/GBS-scrollScenePlugin#1]
I made a new project in GB Studio, set scenes to platformer, assigned tilesets, added Set Neighbour Scene event, created trigger and added Change scene.

The project does not scroll to the new screen on other modes, it only functions in Topdown2D. If I change the first scene to Topdown2D it can scroll in to a platformer scene. But it cannot scroll from a platformer scene.
[platformscrolltester.zip](https://github.com/user-attachments/files/16124548/platformscrolltester.zip)

**Comment by Mico27** [comment]
You dont need to put a trigger with load scene to change scene, just adding the "set neighbour scene" event in the init of the scene is enough. If you remove the trigger it'll work.
